- name: Add the user 'admin' with a bash shell to the user's groups
  user:
      name: admin
      password: "{{ 'admin' | password_hash('sha512') }}"
      create_home: yes
      shell: /bin/bash

- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
      path: /etc/hosts
      line: "{{ item.value }} {{ item.key }}"

- name: copy invoices2019.zip
  copy:
      src: ../files/invoices2019.zip
      dest: /home/admin/invoices2019.zip
      owner: admin
      mode: '640'

- name: install nfs server
  action: apt pkg=nfs-kernel-server state=present update_cache=yes
  tags:
    - nfs

- name: ensure nfs service is running (Ubuntu)
  action: service name={{item}} state=started
  tags:
    - nfs
  with_items:
    - nfs-kernel-server
